Fix for NPE when no podman machines exist
The symptom is a blank screen on startup.

The cause is this error:
```
TypeError: Cannot read properties of undefined (reading 'Running')
at PodmanClientEngineVirtualized.isControllerScopeAvailable
```

This is because no machines exist, that is empty output of

```bash
podman machine list
```